# Header
#logo: /img/bimmer-sticker-store-logo-new.svg
logo: /img/sticker-store-llc-logo.svg

# Jumbotron
slogan: Stickers, Decals and Windshield Banners for Your Car
lead1: We design and manufacture vinyl stickers for cars and trucks. We offer a selection of decals for various car brands including BMWs.
lead2: "Contour cut stickers, <a href='/custom-windshield-banner-sun-strip/'>custom windshield banners</a> with your text and colors, <a href='/custom-social-media-stickers/'>social network stickers</a> for your Instagram, YouTube and other profiles."

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png

# Social
facebook_url: https://www.facebook.com/bimmersticker.store/
instagram_url: https://www.instagram.com/bimmersticker.store/
twitter_url: https://twitter.com/bimmersticker
email: "&#105;&#110;f%6f%40b&#105;%6dme%72st%69&#99;k%65r.%73tor%65"
formcarry_url: https://formcarry.com/s/2GJ-ONB1eLi
googlereview_url: https://g.page/r/CeSNA8SNuJeNEAg/review
googlemaps_url: https://g.page/sticker-store-llc?gm