# Header
logo: /img/bimmer-sticker-store-logo-new.svg

# Jumbotron
slogan: Vinyl Stickers for Your Car
lead1: We specialize on making vinyl stickers for BMW vehicles and other car brands.
lead2: Contour cut stickers, sun strips and windshield banners. <a href="mailto:info@bimmersticker.store">Shoot us an email</a> for custom orders.

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png

# Social
facebook_url: https://www.facebook.com/bimmersticker.store/
instagram_url: https://www.instagram.com/bimmersticker.store/
twitter_url: https://twitter.com/bimmersticker
email: "&#105;&#110;f%6f%40b&#105;%6dme%72st%69&#99;k%65r.%73tor%65"
formcarry_url: https://formcarry.com/s/2GJ-ONB1eLi
googlereview_url: https://g.page/r/CeSNA8SNuJeNEAg/review