# Header
logo: /img/sticker-store-llc-logo.svg
logo_dark: /img/sticker-store-llc-logo-dark.svg

# Jumbotron
slogan: Stickers, Decals and Windshield Banners for Your Car
lead1: We design and manufacture vinyl stickers for cars, trucks and commercial fleet.
lead2: "Contour cut stickers, inkjet printed decals, <a href='/custom-windshield-banner-sun-strip/'>windshield banners</a> with custom text and colors, stickers for <a href='/custom-social-media-stickers/'>social media platforms</a> and <a href='/custom-truck-van-decals/'>business decals for trucks and vans</a>."

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png

# Social
facebook_url: https://www.facebook.com/bimmersticker.store/
etsy_url: https://www.etsy.com/shop/StickerStoreLLC
instagram_url: https://www.instagram.com/bimmersticker.store/
twitter_url: https://twitter.com/bimmersticker
email: "&#105;&#110;f%6f%40b&#105;%6dme%72st%69&#99;k%65r.%73tor%65"
formcarry_url: https://formcarry.com/s/2GJ-ONB1eLi
# googlereview_url: https://g.page/r/CeSNA8SNuJeNEAg/review
googlemaps_url: https://g.page/sticker-store-llc?gm
messenger_url: m.me/376346382812240