[[redirects]]
  from = "/font/*"
  to = "https://d3ui957tjb5bqd.cloudfront.net/op/font-preview/:splat"
  status = 200
  force = true
  [redirects.headers]
    Cache-Control = "no-store"
    Pragma = "no-cache"